export const data = [
  {
    key: "1",
    active: true,
    usertype: "Internal",
    name: "kabir123",
    clientname: "Bhavsar Kabir",
    age: 32,
    rollname: "Admin",
    email: "bhavsar.kabir@example.com",
    contactno: "9012343231",
    address: "New York No. 1 Lake Park",
  },
  {
    key: "2",
    active: false,
    usertype: "Internal",
    name: "meet900",
    clientname: "Meet Murabiya",
    age: 42,
    rollname: "User",
    email: "meet.murabiya@example.com",
    contactno: "9072838485",
    address: "London No. 1 Lake Park",
  },
  {
    key: "3",
    active: false,
    usertype: "External",
    name: "tatsam32",
    clientname: "Tatsam Rai",
    age: 32,
    rollname: "Admin",
    email: "tatsam.rai@example.com",
    contactno: "4345367367",
    address: "Sydney No. 1 Lake Park",
  },
  {
    key: "4",
    active: true,
    usertype: "External",
    name: "gaurav123",
    clientname: "Gaurav Patel",
    age: 32,
    rollname: "User",
    email: "gaurav@example.com",
    contactno: "1234567890",
    address: "London No. 2 Lake Park",
  },
];
